baseurl: "https://postreview.org"
languageCode: "en-us"
title: "PostReview"
theme: "Blonde"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true
paginate: 6

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Submit a Review
      url: /submit-review/
      weight: 1.5
    - name: Support Project
      url: /support-project/
      weight: 1.7
    - name: About
      url: /about/
      weight: 2
# Blonde Paramss
params:
  paginator_pages: '5'
  archive_dropdown: 'false'
  tagsLimit: 20
  post:
    thumbnail_height: h-48
    thumbnail_width: w-48
  widgets:
    archives: true
    categories: true
    tags: true
    recentposts: false
    search: true

markup:
  goldmark:
    renderer:
      unsafe: false
